### ISSUE TITLE
Does this library need to be re-released to get new versions of @jbrowse/react-linear-genome-view

### ISSUE THREAD

**Issue by cmdcolin** [GMOD/jbrowse-jupyter#21]
See question title. I am curious if this package or dash_jbrowse need to be have a new release to get updated versions of @jbrowse/react-linear-genome-view

**Comment by cmdcolin** [comment]
I see that https://github.com/GMOD/dash_jbrowse/blob/main/package.json#L31 is a semver string which implies it can get updates but it also has a package-lock.json which implies it could be frozen(?)

**Comment by teresam856** [comment]
We would need to update dash JBrowse to get the latest versions of the `react linear genome view` (and in the future any other embeddable components that we add to the dash jbrowse suite). Dash JBrowse will build  the JS component and translate it into something that python can make sense of. Could automate the process with a github actions? There should be a PR available [here](https://github.com/GMOD/dash_jbrowse/pull/19) if we think it could help make the process easier. Then this package would only keep track of the python dash jbrowse package (ideally since we do not aim to change the view state of the embedabble components, then we would not need to update jupyter jbrowse as long as there are no breaking changes).

**Comment by teresam856** [comment]
Automating the release process for dash_jbrowse was accomplished through these two pr https://github.com/GMOD/dash_jbrowse/pull/24 and https://github.com/GMOD/dash_jbrowse/pull/19.
Could add the same github action workflows to this package to make it easier to upgrade any package versions.

**Comment by teresam856** [comment]
Added workflows in these PRs: https://github.com/GMOD/jbrowse-jupyter/pull/28, https://github.com/GMOD/jbrowse-jupyter/pull/26
